### ISSUE TITLE
Question: What are the .a files?

### ISSUE THREAD

**Issue by hajimehoshi** [ebiten-playground/ebiten-playground.github.io#1]
Thank you for inviting!

I was wondering what the .a files in pkg directory are. Is this necessary to compile something?

**Comment by j7b** [comment]
You're welcome!

Yes, the .a files are used to resolve packages by the gopherjs compiler. Upstream renames these to a.js but that's a confusing convention and astonishes when people try to view source.

**Comment by hajimehoshi** [comment]
Confirmed that they are binary-formatted but include JavaScript sources. Thank you for explanation.
