### ISSUE TITLE
Use sandbox attribute for iframe

### ISSUE THREAD

**Issue by hajimehoshi** [ebiten-playground/ebiten-playground.github.io#12]

**Comment by j7b** [comment]
It's mostly redundant because the iframe needs top and web api's so it can't stop the most malicious script that occurs to me.

**Comment by hajimehoshi** [comment]
https://github.com/ebiten-playground/ebiten-playground.github.io/commit/0cbb22c602c860ed31b8d1aa0cece74658a2be3a

I forgot I've already added sandbox attribute.

> It's mostly redundant because the iframe needs top and web api's so it can't stop the most malicious script that occurs to me.

Yeah, that's true. Let's revisit this if we actually need a stricter sandbox.

**Comment by hajimehoshi** [comment]
https://github.com/ebiten-playground/ebiten-playground.github.io/commit/ab760c821fe38629f16f94442da30d8f29c8082d

I've succeeded to remove 'allow-same-origin'. The iframe can no longer access the top window.

~~It looks like localStorage or workers are still available, and this is a different problem IIUC.~~ EDIT: localStorage is not available without allow-same-origin.

**Comment by hajimehoshi** [comment]
Ugh, I found that setting sandbox doesn't take effect if it is too late. Reverted partly.
