### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by hajimehoshi** [ebiten-playground/ebiten-playground.github.io#14]
If you don't have a strong opinion, I'd like to change the indentation from 4 space chars to 2 space chars. (EDIT: I'm talking about *.html and *.js files)

@j7b, what do you think?

**Comment by j7b** [comment]
SGTM I think that's how it would have been if I'd bother to hit cmd-alt-f in vs code before I saved it.

**Comment by hajimehoshi** [comment]
Thank you!
