### ISSUE TITLE
Go.Compile fails with a message `(image.Rectangle).Dx`

### ISSUE THREAD

**Issue by hajimehoshi** [ebiten-playground/ebiten-playground.github.io#22]
Minimized test case:

http://ebiten-playground.github.io/#/bd945dbd8d2eb52059037e2679bedb0c15efd7f7085b9f3cda8ae6fb495b769a

```
package main

import (
        "github.com/hajimehoshi/ebiten"
)

var ebitenImage *ebiten.Image

func main() {
        if 0 > 320-ebitenImage.Bounds().Dx() {
        }
}
```

**Comment by hajimehoshi** [comment]
It looks like imported path is solved at g.importContext.Import and the panic happens just after compiling `github.com/hajimehoshi/ebiten` and before compiling `image`. I think using goroutines introduced unexpected behavior. This should be related to https://github.com/j7b/jsplayground/issues/2 .

**Comment by j7b** [comment]
Upstream playground fails similarly

**Comment by hajimehoshi** [comment]
OK so the problem is in playground.js.

I investigated other usages of `compiler.ImportDependencie` like https://github.com/gopherjs/gopherjs/blob/master/build/build.go.  The given unnamed function calls  `buildImportPathWithSrcDir`, that calls `BuildPackage`, that calls `buildImportPathWithSrcDir` for each imported package recursively. Thus, I think `g.importContext.Import` should do the same recursive thing instead of reading only one package. We would be able to keep goroutines in `Import`, but I think we should remove that not to introduce another unexpected behavior in the future.

**Comment by j7b** [comment]
It can't really do that asynchronously without doing a lot of inspection that gets kind of complicated.

A four line change to jsplayground that fixes it is to compile twice if any packages were fetched if err != nil which I think is intended in upstream's approach but fails in cases like this where the package is resolved but too late for another dependency. You'll note the 2nd time you press run it compiles.

**Comment by hajimehoshi** [comment]
> You'll note the 2nd time you press run it compiles.

Yeah, that's true. I printf-ed at the import function and found how importing worked.

If you are busy, shall I fix this?

**Comment by j7b** [comment]
I got, fixing other issues too.

**Comment by hajimehoshi** [comment]
OK, I'll do tonight. What part are you fixing?

**Comment by j7b** [comment]
I fixed and fixed some other stuff will build soon.

**Comment by hajimehoshi** [comment]
https://github.com/j7b/jsplayground is not updated yet. Have you updated that on your local machine?

**Comment by j7b** [comment]
Yes will be pushing soon.

**Comment by j7b** [comment]
Fixed

**Comment by hajimehoshi** [comment]
👍 

https://ebiten-playground.github.io/#/bd945dbd8d2eb52059037e2679bedb0c15efd7f7085b9f3cda8ae6fb495b769a should show error (nil reference) but not. Is this a regression?

**Comment by j7b** [comment]
No, I don't think there was a panic handler.

**Comment by hajimehoshi** [comment]
But Go error should be shown on the console, right?

**Comment by hajimehoshi** [comment]
> But Go error should be shown on the console, right?

Ah sorry the original state didn't handle such Go errors. Please ignore this.

Thank you for fixing.
