### ISSUE TITLE
Question: how to generate js files

### ISSUE THREAD

**Issue by Noofbiz** [ebiten-playground/ebiten-playground.github.io#28]
Hello, I am wondering what the process is for generating the Javascript for jsplayground.js / jsplayground.js.map and the pkg directory. Is it just from building the gopherjs playground, or is there another way?

**Comment by hajimehoshi** [comment]
Hi, 

https://github.com/j7b/jsgen and https://github.com/j7b/jsplayground generate file for the playground. I'm now remembering the details...

**Comment by hajimehoshi** [comment]
@j7b should know better

**Comment by Noofbiz** [comment]
Thank you for the help!
